First commit
yankovskaya/LearnPy-Homework pull request #1
Opened 2022-02-15 12:31 UTC by yankovskaya

2022-02-15 15:23 UTC, vppuzakov requested changes
👍 в целом все хорошо, осталось немножко по комментам доделать

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/simple.py
> +v = v + 10
🔴 тут ошибка, попробуй запустить эти строки (14-16) непосредственно в `ipython`

`input` возвращает строку, а складывать мы можем только числа
нужно преобразовать строку в число с помощью `int()`

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/simple.py
> +print(f'Привет, {name}! Как дела?')
👍

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/functions.py
> +result = get_sum('Learn', 'python').upper()
👍

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/functions.py
> +    one = str(one)
👍 верно, можно привести к строке явно вызвав `str()`

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/functions.py
> +    return str(one + delimiter + two)
🔴 тут приведение к строке лишнее, ведь результатом сложения двух строк уже будет строка

то есть можно было бы оставить: `return one + delimiter + two`

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/functions.py
> +    return str(one + delimiter + two)
🔴 но складывать строки не так здорово как использовать `str.format` или `f-string`

```python
return f'{firstname} {lastname}'
```

или в сложных случаях:

```python

school = {
    'students': [
        {'firstname': 'Ivan', 'lastname': 'Petrov'},
        {'firstname': 'Mick', 'lastname': 'Sidorov'},
    ]
}

return '{firstname} {lastname}'.format(
    firstname=school['students'][0]['firstname]],
    lastname=school['students'][0]['lastname']],
)
```

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/functions.py
> +    delimiter = str('&')
'&' - уже строка - необязательно вызывать str()

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/price.py
> +def format_price(price):
👍

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/lists.py
> +li = [3, 5, 7, 9, 10.5]
👍 отлично

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/lists.py
> +print(li[5])
💡 так сработает, но лучше воспользовать отрицательным индексом `li[-1]`

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/lists.py
> +print(li[2:5])
💡 когда просят вывести первый / второй и тд элементы списка - имеют ввиду подобного рода запись `li[0:1]` - то есть фактически первый и второй элементы вне зависимости от факта, что индексация с нуля ведется.

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/dictionaries.py
> +dictionary = [{"city": "Москва", "temperature": "20"}]
💡 не совсем верно, все же требовался просто словарь, а у нас получился список словарей

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/dictionaries.py
> +print(dictionary[0]["city"])
👍

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/dictionaries.py
> +dictionary[0]["temperature"] = "15"
🔴 не, так нельзя - считается, что мы не знаем какое там значение

то есть надо взять текущее значение температуры, привести его к числу, вычесть из него 5 и не забыть привести к строке

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/dictionaries.py
> +print(dictionary.get("country"))
💡 так тоже можно проверить, но иногда можно использовать другой способ:

```python
'country' in dictionary
```

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/dictionaries.py
> +print(dictionary.get("country", "Россия"))
👍

2022-02-15 15:23 UTC, vppuzakov commented on lesson1/dictionaries.py
> +print(len(dictionary))
👍

2022-02-16 14:34 UTC, yankovskaya commented on lesson1/dictionaries.py
> +dictionary[0]["temperature"] = "15"
Я переделала и результат верный, но получилось довольно много строк. Есть ли вариант сделать решение короче?
dictionary["temperature"] = int(dictionary["temperature"])
dictionary["temperature"] = dictionary["temperature"] - 5
dictionary["temperature"] = str(dictionary["temperature"])
print(dictionary)

2022-02-16 14:35 UTC, yankovskaya commented on lesson1/dictionaries.py
> +print(dictionary.get("country"))
Спасибо, учла!

2022-02-16 14:36 UTC, yankovskaya commented on lesson1/functions.py
> +    return str(one + delimiter + two)
спасибо, проглядела(

2022-02-16 14:38 UTC, yankovskaya commented on lesson1/functions.py
> +    return str(one + delimiter + two)
Действительно намного лучше, спасибо!

2022-02-16 14:39 UTC, yankovskaya commented on lesson1/lists.py
> +print(li[2:5])
Исправила!

2022-02-16 16:33 UTC, vppuzakov approved these changes

2022-02-16 16:34 UTC, merged